services:
  - type: web
    name: comem-modeldon
    runtime: static
    buildCommand: npm ci && node scripts/build-all.mjs --force
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
    routes:
      - type: rewrite
        source: /01-introduction/*
        destination: /01-introduction/index.html
      - type: rewrite
        source: /02-modele-conceptuel/*
        destination: /02-modele-conceptuel/index.html
      - type: rewrite
        source: /03-modele-logique/*
        destination: /03-modele-logique/index.html
      - type: rewrite
        source: /04-modele-physique/*
        destination: /04-modele-physique/index.html
      - type: rewrite
        source: /05-interroger/*
        destination: /05-interroger/index.html
      - type: rewrite
        source: /06-connecter/*
        destination: /06-connecter/index.html
      - type: rewrite
        source: /07-analyser/*
        destination: /07-analyser/index.html
      - type: rewrite
        source: /08-optimiser/*
        destination: /08-optimiser/index.html
      - type: rewrite
        source: /09-semi-structure/*
        destination: /09-semi-structure/index.html
